In [82]:
# import file : 

import pandas as pd
import numpy as np
data="2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv"
df = pd.read_csv(data)
df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581)
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755)
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163)

In [83]:
# number of files :

df.shape

(3023, 31)

In [84]:
# total of missing values :

df.isnull().sum()

X                                                0
Y                                                0
Unique Squirrel ID                               0
Hectare                                          0
Shift                                            0
Date                                             0
Hectare Squirrel Number                          0
Age                                            121
Primary Fur Color                               55
Highlight Fur Color                           1086
Combination of Primary and Highlight Color       0
Color notes                                   2841
Location                                        64
Above Ground Sighter Measurement               114
Specific Location                             2547
Running                                          0
Chasing                                          0
Climbing                                         0
Eating                                           0
Foraging                                         0
Other Activities                              2586
Kuks                                             0
Quaas                                            0
Moans                                            0
Tail flags                                       0
Tail twitches                                    0
Approaches                                       0
Indifferent                                      0
Runs from                                        0
Other Interactions                            2783
Lat/Long                                         0
dtype: int64

In [89]:
# count the number of nan in each column :

s = df.isnull().apply(sum, axis=0)

# delete columns that have more than 50 missing values : 

for col in df: 
   if s[col] >= 50:  
       del df[col]
print(df.shape)
df.head()

(3023, 22)

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Combination of Primary and Highlight Color,Running,Chasing,...,Foraging,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,+,False,False,...,False,False,False,False,False,False,False,False,False,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Gray+Cinnamon,True,False,...,False,False,False,False,False,False,False,False,True,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Cinnamon+,False,False,...,False,False,False,False,False,False,False,True,False,POINT (-73.9768311751004 40.76671780725581)
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Gray+,False,False,...,False,False,False,False,False,False,False,False,True,POINT (-73.9757249834141 40.7697032606755)
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,+,False,False,...,False,True,False,False,False,False,False,False,False,POINT (-73.9593126695714 40.797533370163)

In [91]:
df = df.drop(['Lat/Long'], axis=1) # delete the "Lat/Long" column => already x and y, easier to use

In [92]:
print(df.shape)
df.head()

(3023, 21)

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Combination of Primary and Highlight Color,Running,Chasing,...,Eating,Foraging,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,+,False,False,...,False,False,False,False,False,False,False,False,False,False
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Gray+Cinnamon,True,False,...,False,False,False,False,False,False,False,False,False,True
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Cinnamon+,False,False,...,False,False,False,False,False,False,False,False,True,False
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Gray+,False,False,...,False,False,False,False,False,False,False,False,False,True
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,+,False,False,...,False,False,True,False,False,False,False,False,False,False

In [66]:
# save into a .csv file :

smaller_df = df.to_csv('smaller_df.csv', index = False)

# Columns :

# Dealing with missing values :

In [67]:
#liste of missing values :

missing_values = ["","+","na","n/a","nan"," "]
smaller_df = pd.read_csv("smaller_df.csv", na_values=missing_values)

smaller_df.isnull().sum()

X                                              0
Y                                              0
Unique Squirrel ID                             0
Hectare                                        0
Shift                                          0
Date                                           0
Hectare Squirrel Number                        0
Combination of Primary and Highlight Color    55
Running                                        0
Chasing                                        0
Climbing                                       0
Eating                                         0
Foraging                                       0
Kuks                                           0
Quaas                                          0
Moans                                          0
Tail flags                                     0
Tail twitches                                  0
Approaches                                     0
Indifferent                                    0
Runs from                                      0
dtype: int64

In [68]:
# showing the Combinaison column :

smaller_df["Combination of Primary and Highlight Color"].unique()

array([nan, 'Gray+Cinnamon', 'Cinnamon+', 'Gray+', 'Cinnamon+White',
       'Gray+White', 'Cinnamon+Gray', 'Gray+Cinnamon, White',
       'Cinnamon+Gray, White', 'Gray+Black, Cinnamon, White', 'Black+',
       'Gray+Black', 'Black+White', 'Black+Cinnamon', 'Gray+Black, White',
       'Cinnamon+Black', 'Black+Gray', 'Gray+Black, Cinnamon',
       'Black+Cinnamon, White', 'Cinnamon+Black, White',
       'Black+Gray, White', 'Cinnamon+Gray, Black'], dtype=object)

# Dealing with rows :

In [69]:
# showing all the uniques values for check :

for elements in smaller_df:
    print("      ##########",elements,"##########")
    print(smaller_df[elements].unique())

      ########## X ##########
[-73.95613449 -73.95704377 -73.97683118 ... -73.9665872  -73.96399412
 -73.97547942]
      ########## Y ##########
[40.79408239 40.79485094 40.76671781 ... 40.78367751 40.78991523
 40.76964045]
      ########## Unique Squirrel ID ##########
['37F-PM-1014-03' '37E-PM-1006-03' '2E-AM-1010-03' ... '22D-PM-1012-07'
 '29B-PM-1010-02' '5E-PM-1012-01']
      ########## Hectare ##########
['37F' '37E' '02E' '05D' '39B' '33H' '06G' '35C' '07B' '32E' '13E' '11H'
 '36H' '33F' '21C' '11D' '20B' '36I' '05C' '07H' '16C' '14E' '32A' '17F'
 '16I' '12I' '32F' '25A' '15E' '39G' '29I' '07E' '17C' '10A' '28A' '22F'
 '12B' '18A' '29C' '38C' '31H' '08H' '34F' '13H' '17E' '02B' '19D' '40B'
 '03E' '39C' '14F' '06I' '15F' '08B' '03A' '05E' '05F' '11B' '16E' '13F'
 '29H' '23C' '33C' '38G' '16G' '35A' '28C' '32D' '22A' '19C' '15G' '10F'
 '42E' '22B' '05A' '32H' '42C' '41D' '21G' '07F' '38F' '41B' '36A' '31A'
 '42G' '37D' '24B' '07G' '15I' '19B' '13D' '35B' '40D' '38B' '40I' '40A'
 '03B' '21D' '10B' '41A' '02F' '26A' '35E' '11G' '07A' '03D' '35D' '18G'
 '06F' '09F' '38E' '33G' '32G' '04D' '06H' '15D' '39H' '20F' '09G' '23F'
 '39A' '13A' '10G' '13C' '32C' '31D' '18C' '40E' '04G' '12F' '17H' '03G'
 '15H' '14G' '42H' '38A' '22C' '36F' '30D' '05I' '16D' '06D' '12E' '14D'
 '22D' '08A' '02D' '12C' '08F' '02H' '32B' '04E' '14A' '09B' '08C' '06B'
 '03C' '38D' '10C' '26I' '01B' '09A' '37H' '06A' '32I' '04B' '31F' '23D'
 '30B' '04F' '33I' '37C' '33B' '37I' '37G' '20A' '15A' '16F' '01G' '37B'
 '03I' '12G' '10I' '19H' '34I' '12A' '19F' '20C' '36E' '28D' '21E' '39F'
 '27A' '18D' '27I' '14I' '01H' '30E' '16A' '11E' '22I' '41C' '29B' '15B'
 '18I' '12D' '11F' '34D' '20D' '21F' '33D' '08E' '33E' '31G' '02C' '04I'
 '40C' '10H' '36C' '11I' '01D' '22G' '40G' '01C' '07I' '14H' '08I' '13B'
 '34H' '04A' '42F' '41I' '12H' '09C' '36B' '31E' '21B' '29D' '42D' '19G'
 '13I' '24A' '36D' '42B' '41E' '18F' '16H' '09D' '07D' '08G' '04C' '23E'
 '30A' '15C' '16B' '11A' '36G' '14C' '21H' '05G' '03F' '42I' '14B' '01A'
 '09I' '18H' '26B' '28I' '01F' '31I' '17A' '03H' '02A' '30I' '09E' '39D'
 '34E' '17D' '21A' '13G' '35F' '38I' '09H' '30C' '19E' '08D' '04H' '23B'
 '20G' '17G' '35G' '02I' '10D' '17I' '42A' '34B' '17B' '11C' '33A' '31B'
 '25I' '37A' '01E' '22H' '34A' '19A' '06C' '07C' '05B' '23A' '02G' '35H'
 '06E' '41G' '40H' '39I' '23I' '31C' '29A' '22E' '41F' '28B' '35I' '24I'
 '23H' '34C' '39E' '01I' '18E' '27B' '34G' '05H' '40F' '30H' '10E' '25B'
 '20E' '38H' '30F']
      ########## Shift ##########
['PM' 'AM']
      ########## Date ##########
[10142018 10062018 10102018 10182018 10192018 10202018 10132018 10082018
 10172018 10072018 10122018]
      ########## Hectare Squirrel Number ##########
[ 3  5  1  2  9 14 23  7  4  6 13 10 16  8 11 12 20 15 19 17 21 22 18]
      ########## Combination of Primary and Highlight Color ##########
[nan 'Gray+Cinnamon' 'Cinnamon+' 'Gray+' 'Cinnamon+White' 'Gray+White'
 'Cinnamon+Gray' 'Gray+Cinnamon, White' 'Cinnamon+Gray, White'
 'Gray+Black, Cinnamon, White' 'Black+' 'Gray+Black' 'Black+White'
 'Black+Cinnamon' 'Gray+Black, White' 'Cinnamon+Black' 'Black+Gray'
 'Gray+Black, Cinnamon' 'Black+Cinnamon, White' 'Cinnamon+Black, White'
 'Black+Gray, White' 'Cinnamon+Gray, Black']
      ########## Running ##########
[False  True]
      ########## Chasing ##########
[False  True]
      ########## Climbing ##########
[False  True]
      ########## Eating ##########
[False  True]
      ########## Foraging ##########
[False  True]
      ########## Kuks ##########
[False  True]
      ########## Quaas ##########
[False  True]
      ########## Moans ##########
[False  True]
      ########## Tail flags ##########
[False  True]
      ########## Tail twitches ##########
[False  True]
      ########## Approaches ##########
[False  True]
      ########## Indifferent ##########
[False  True]
      ########## Runs from ##########
[False  True]

In [100]:
# delete rows with missing values :

cleaned_df = smaller_df.dropna()
print(cleaned_df.shape)
cleaned_df

(2968, 21)

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Combination of Primary and Highlight Color,Running,Chasing,...,Eating,Foraging,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Gray+Cinnamon,True,False,...,False,False,False,False,False,False,False,False,False,True
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Cinnamon+,False,False,...,False,False,False,False,False,False,False,False,True,False
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Gray+,False,False,...,False,False,False,False,False,False,False,False,False,True
5,-73.956570,40.790256,33H-AM-1019-02,33H,AM,10192018,2,Gray+Cinnamon,False,False,...,False,False,False,False,False,False,False,False,False,False
6,-73.971974,40.769305,6G-PM-1020-02,06G,PM,10202018,2,Gray+,True,True,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Gray+,False,False,...,True,True,False,False,False,False,False,False,False,True
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Gray+White,False,False,...,False,True,False,False,False,False,False,False,True,False
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,"Gray+Black, Cinnamon, White",False,False,...,True,True,False,False,False,False,False,False,True,False
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,"Gray+Cinnamon, White",False,False,...,True,False,False,False,False,False,False,False,True,False
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,"Cinnamon+Gray, White",False,False,...,True,True,False,False,False,False,False,True,False,False

In [93]:
cleaned_df.shape

(3023, 21)

In [101]:
# save into a .csv file :

clean_df = cleaned_df.to_csv('clean_df.csv', index = False)